name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Clean workspace
      run: rm -rf node_modules/
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Test
      run: npm test || true
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact-${{ matrix.node-version }}
        path: dist/
        retention-days: 1
        compression-level: 9

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Clean Docker cache
      run: docker system prune -a --force
    
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact-18.x
        path: dist
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set lowercase owner name
      shell: bash
      run: |
        echo "OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.OWNER_LC }}/inspection-system:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
